version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    groups:
      cargo:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      docker:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /webui
    schedule:
      interval: monthly
    # typescript-eslint peers typescript <6.1
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
    groups:
      npm:
        patterns:
          - "*"
