CREATE TABLE READING_EVENT (
    ID integer PRIMARY KEY AUTOINCREMENT,
    USER_ID varchar NOT NULL,
    BOOK_ID varchar NOT NULL,
    SERIES_ID varchar NOT NULL,
    PAGE int NOT NULL,
    CREATED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx__reading_event__user_date ON READING_EVENT (USER_ID, CREATED_DATE);
CREATE INDEX idx__reading_event__user_book_date ON READING_EVENT (USER_ID, BOOK_ID, CREATED_DATE);
