CREATE TABLE SMART_LIST (
    ID varchar PRIMARY KEY,
    NAME varchar NOT NULL,
    SUMMARY varchar NOT NULL DEFAULT '',
    OWNER_USER_ID varchar NOT NULL,
    TARGET varchar NOT NULL CHECK (TARGET IN ('BOOK', 'SERIES')),
    VISIBILITY varchar NOT NULL DEFAULT 'PRIVATE' CHECK (VISIBILITY IN ('PRIVATE', 'PUBLIC', 'SHARED')),
    SEARCH_JSON varchar NOT NULL,
    CREATED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx__smart_list__owner ON SMART_LIST (OWNER_USER_ID);

CREATE TABLE SMART_LIST_SHARE (
    SMART_LIST_ID varchar NOT NULL,
    USER_ID varchar NOT NULL,
    PRIMARY KEY (SMART_LIST_ID, USER_ID)
);
CREATE INDEX idx__smart_list_share__user ON SMART_LIST_SHARE (USER_ID);

CREATE TABLE SMART_LIST_THUMBNAIL (
    ID varchar PRIMARY KEY,
    SMART_LIST_ID varchar NOT NULL,
    THUMBNAIL blob NOT NULL,
    FINGERPRINT varchar NOT NULL,
    SELECTED boolean NOT NULL DEFAULT 0,
    TYPE varchar NOT NULL DEFAULT 'GENERATED',
    MEDIA_TYPE varchar NOT NULL DEFAULT 'image/jpeg',
    FILE_SIZE int,
    WIDTH int,
    HEIGHT int,
    CREATED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx__smart_list_thumbnail__smart_list ON SMART_LIST_THUMBNAIL (SMART_LIST_ID);
