CREATE TABLE TRACKER_LINK (
    SERIES_ID varchar NOT NULL,
    USER_ID varchar NOT NULL,
    PROVIDER varchar NOT NULL CHECK (PROVIDER IN ('anilist', 'mal', 'bangumi', 'mangabaka')),
    TRACK_ID varchar NOT NULL,
    TITLE varchar,
    TRACK_MODE varchar NOT NULL DEFAULT 'auto' CHECK (TRACK_MODE IN ('auto', 'chapter', 'volume')),
    CHAPTER_OFFSET int NOT NULL DEFAULT 0,
    CREATED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (SERIES_ID, USER_ID, PROVIDER)
);
CREATE INDEX idx__tracker_link__user ON TRACKER_LINK (USER_ID);

CREATE TABLE TRACKER_PREFERENCES (
    USER_ID varchar PRIMARY KEY,
    LIBRARY_IDS varchar NOT NULL DEFAULT '[]',
    DEFAULT_TRACKER varchar NULL,
    LAST_MODIFIED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);
