//! DAO layer. Conventions:
//! - Reads go through `db.ro()?`, writes through `db.rw()?`.
//! - datetime columns are read/written via `time_codec` (TEXT, UTC); bool columns
//!   are INTEGER 0/1; enums are stored as `as_str()`.
//! - Row mapping returns `rusqlite::Result` (parse failures become
//!   `FromSqlConversionFailure`); DAO methods return `crate::Result`.
//! - New entity IDs are generated by the `TsidFactory` inside each DAO.

use komga_core::time_codec;
use rusqlite::{Error as SqlError, Row};
use time::OffsetDateTime;

pub mod book;
pub mod book_projection;
pub mod collection;
pub mod history;
pub mod komf_integration;
pub mod library;
pub mod media;
pub mod page_hash;
pub mod read_progress;
pub mod readlist;
pub mod series;
pub mod series_metadata_contribution;
pub mod settings;
pub mod sidecar;
pub mod sync_point;
pub mod tasks;
pub mod thumbnail;
pub mod thumbnail_migration;
pub mod user;

pub use library::LibraryDao;

pub(crate) fn invalid_column(row: &Row<'_>, idx: usize, what: &str, value: &str) -> SqlError {
    let stmt = row.as_ref();
    let col = stmt.column_name(idx).unwrap_or("?");
    // DAO selects lead with the entity id, so column 0 identifies the failing row
    let row_ctx = if idx > 0 {
        match (stmt.column_name(0), row.get::<_, String>(0)) {
            (Ok(key), Ok(id)) => format!(" (row {key}={id})"),
            _ => String::new(),
        }
    } else {
        String::new()
    };
    SqlError::FromSqlConversionFailure(
        idx,
        rusqlite::types::Type::Text,
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("invalid {what} in column {col}: {value}{row_ctx}"),
        )
        .into(),
    )
}

pub fn get_datetime(row: &Row<'_>, idx: usize) -> rusqlite::Result<OffsetDateTime> {
    let s: String = row.get(idx)?;
    time_codec::parse_datetime_utc(&s).ok_or_else(|| invalid_column(row, idx, "datetime", &s))
}

pub fn get_datetime_opt(row: &Row<'_>, idx: usize) -> rusqlite::Result<Option<OffsetDateTime>> {
    let s: Option<String> = row.get(idx)?;
    match s {
        Some(s) => time_codec::parse_datetime_utc(&s)
            .map(Some)
            .ok_or_else(|| invalid_column(row, idx, "datetime", &s)),
        None => Ok(None),
    }
}

pub(crate) fn get_date(row: &Row<'_>, idx: usize) -> rusqlite::Result<Option<time::Date>> {
    let s: Option<String> = row.get(idx)?;
    match s {
        Some(s) => time_codec::parse_date(&s)
            .map(Some)
            .ok_or_else(|| invalid_column(row, idx, "date", &s)),
        None => Ok(None),
    }
}
